FROM maven:3.6.1-jdk-11

ADD install-gnupg22.sh /tmp/install-gnupg22.sh

RUN apt-get remove gpg -y && \
	/tmp/install-gnupg22.sh && \
	rm -rf /tmp/install-gnupg22.sh /var/lib/apt/lists/*

ENV PATH="/usr/local/bin/:${PATH}"
